server:
  http:
    addr: ":8080"

transport:
  websocket:
    addr: ":9080"
    path: "/ws"
  grpc:
    addr: ":9090"

broker:
  type: redis
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 10

proxies:
  - name: example
    endpoint: 127.0.0.1:9091
    timeout: 30s
    grpc:
      insecure: true
    routes:
      - channel: chat.messages
        method: "*"